[keyboard]
name = "my-rmk-kb"
product_name = "My RMK Keyboard"
manufacturer = "SideraKB"
vendor_id = 0x5a69
product_id = 0x4643
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_06", "P1_04", "P0_11", "P1_00"]
output_pins = ["P0_09", "P0_10", "P1_11"]
# RMK enables col2row as the default feature, currently configs here do nothing actually
# ref: https://haobogu.github.io/rmk/faq.html#my-matrix-is-row2col-the-matrix-doesnt-work
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        # Layer 0
        ["A",     "B",           "CapsLock"],
        ["Kc1",   "Kc2",         "Kc3"],
        ["LCtrl", "MO(1)",       "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"],
    ],
    [
        # Layer 1
        ["TO(1)", "TT(1)", "TG(2)"],
        ["DF(1)", "_",     "_"],
        ["_",     "_",     "_"],
        ["_",     "_",     "_"],
    ],
]

[light]
# All light pins are high-active by default
capslock.pin = "P0_15"
capslock.low_active = false
# numslock.pin = "P_31"
# numslock.low_active = true

[storage]
enabled = true
# Avoid conflict with bootloader, ref: https://haobogu.github.io/rmk/faq.html#rmk-breaks-my-bootloader
start_addr = 0x000A0000
num_sectors = 2
# Set `clear_storage` to true to clear all the stored info when the keyboard boots, useful when testing the firmware
# clear_storage = true

[ble]
enabled = true
