name: Build Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: thumbv7em-none-eabihf

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Build UF2
        run: cargo make uf2 --release

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            my-rmk-kb.hex
            my-rmk-kb.uf2
